name: App CI - SAST, Test, SCA

on:
  pull_request:
     branches: [ main ]
  push:
     branches: [ main ]

permissions:
   contents: read
   security-events: write

env:
  ACR_REGISTERY: ${{ secrets.ACR_REGISTRY }}

jobs:
   codeql:
      name: CodeQL SAST
      runs-on: ubuntu-latest
      steps:
         - uses: action/checkout@4
         - name: Initialize CodeQL
           uses: github/codeql-action/init@v3
           with:
             language: javascript, python
         - name: Autobuild
           run: |
             pushd frontend && npm ci | true; popd
             pushd backend && python -m pip install -r requirements.txt || true; popd
         - name: Run CodeQl
           uses: github/codeql-action/analyze@v3


   frontend-tests:
     name: Frontend - Install & Tests & Audit
     runs-on: ubuntu-latest
     steps:
      - uses: action/checkout@4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: 18
      - name: Install frontend deps
        run: npm cli --prefix frontend
      - name: Run Lint
        run: nom run lint --prefix frontend
      - name: Run tests
        run: npm test --prefix frontend --if-present
      - name: NPM Audit
        run: npm audit --prefix frontend --audit-level=high || true

   backend-sast-unit:
      name: Backend - Bandit + Pytest
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install backend deps
        run: python -m pip install -r backend/requirements.txt
      - name: Run Bandit (SAST for Python)
        run: |
          pip install bandit
          bandit -r backend -lll -f json -o bandit-result.json || true
      - name: Run pytest
        run: |
          pip install -r backend/requirements-dev.txt || true
          pytest backend/tests --junitxml=pytest-report.xml || true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            pytest-report.xml
            bandit-result.json
