name: Check ACR Secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    runs-on: self-hosted
    steps:
      - name: Print ACR registry info
        shell: powershell
        run: |
          "ACR_REGISTRY: '$env:ACR_REGISTRY'"
          "Length: $($env:ACR_REGISTRY.Length)"

      - name: Print ACR username info
        shell: powershell
        run: |
          "ACR_USERNAME: '$env:ACR_USERNAME'"
          "Length: $($env:ACR_USERNAME.Length)"

      - name: Print ACR password info length
        shell: powershell
        run: |
          "ACR_PASSWORD length: $($env:ACR_PASSWORD.Length)"
