name: Check ACR Secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    runs-on: self-hosted
    steps:
      - name: Print ACR registry info
        shell: powershell
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          "ACR_REGISTRY: '$env:ACR_REGISTRY'"
          "Length: $($env:ACR_REGISTRY.Length)"
          "ACR_USERNAME: '$env:ACR_USERNAME'"
          "Length: $($env:ACR_USERNAME.Length)"
          "ACR_PASSWORD length: $($env:ACR_PASSWORD.Length)"
